# Generated by Django 5.2.4 on 2025-09-22 03:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDeLasAlcaldas',
            fields=[
                ('laid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('cvegeo', models.CharField(blank=True, null=True)),
                ('cve_ent', models.CharField(blank=True, null=True)),
                ('cve_mun', models.CharField(blank=True, null=True)),
                ('nomgeo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'limite_de_las_alcaldas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportesIncidenciau',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id_delito', models.CharField()),
                ('delito', models.CharField()),
                ('categoria_delito', models.CharField()),
                ('impacto_delito', models.CharField()),
                ('anio_hecho', models.IntegerField()),
                ('mes_hecho', models.CharField()),
                ('alcaldia', models.CharField()),
                ('cve_col', models.CharField()),
                ('colonia', models.CharField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=32614)),
            ],
            options={
                'db_table': 'reportes_incidenciau',
                'managed': False,
            },
        ),
    ]
